---
title: "NFL Play Personal Cleaning"
author: "Josh Garzaniti"
date: "2025-09-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load in packages
```{r}
library(ggplot2)
library(ggdark)
library(caret)
library(tidyverse)
library(tidyr)
library(stringr)
library(xgboost)
library(randomForest)
library(ggrepel)
library(nflreadr)
library(nflplotR)
library(nflfastR)
library(mice)
library(lme4)
library(here)
```

##Load in Data via NFLFastR
```{r}
pbp = nflfastR::load_pbp(2025)
```
Filtering out Special Teams  esque Plays (QB Spike and Kneels)
```{r}
pbp = pbp%>%
  filter(play_type %in% c("pass", "run"))

##Filter out players where there was a timeout or penalty
pbp = pbp%>%
  filter(timeout == 0, penalty == 0, two_point_attempt == 0)

```


Remove all of the variables we don't need:
```{r}
pbp = pbp%>%
  select(-play_id, -game_id, -old_game_id, -week, -game_date, -quarter_seconds_remaining,
         -game_half, -quarter_end, -drive, -sp, -qtr, -time, -yrdln, -qb_kneel, -qb_spike,
         -field_goal_result, -field_goal_attempt, -kick_distance, -away_timeouts_remaining, -timeout, -td_team, -td_player_name, -td_player_id, -total_away_score, -posteam_timeouts_remaining, -defteam_timeouts_remaining, -total_home_score, -posteam_score, -defteam_score, -score_differential, -posteam_score_post, -defteam_score_post)%>%
  select(-score_differential_post, -total_home_epa, -total_away_epa, -total_home_rush_epa, -total_away_rush_epa, -total_home_pass_epa, -total_away_pass_epa, -total_home_comp_air_epa,
         -total_away_comp_air_epa, -total_home_comp_yac_epa, -total_away_comp_yac_epa, -total_home_raw_air_epa, -total_away_raw_air_epa, -total_home_comp_yac_epa, -total_away_comp_yac_epa, -wp, -def_wp, -vegas_wpa, -vegas_home_wpa, -vegas_wp, -vegas_home_wp, -home_wp_post, -away_wp_post, -total_home_rush_wpa, -total_away_rush_wpa, -total_home_comp_air_wpa, -total_away_comp_air_wpa, -total_home_comp_yac_wpa, -total_away_comp_yac_wpa, -total_home_raw_air_wpa, -total_away_raw_air_wpa)%>%
  select(-total_home_raw_yac_wpa, -total_away_raw_yac_wpa, -punt_blocked, -first_down_penalty, -touchback, -punt_inside_twenty, -punt_in_endzone, -punt_out_of_bounds, -punt_downed, -punt_fair_catch, -kickoff_inside_twenty, -kickoff_in_endzone, -kickoff_out_of_bounds, -kickoff_downed, -kickoff_fair_catch, -fumble_not_forced, -penalty, -penalty_team, -fumble_forced, -own_kickoff_recovery, -own_kickoff_recovery_td, -own_kickoff_recovery_player_id, -own_kickoff_recovery_player_name, -return_touchdown, -extra_point_attempt, -two_point_attempt, -kickoff_attempt, -punt_attempt, -lateral_reception, -lateral_rush, -lateral_return, -lateral_recovery, -passer_player_id, -receiver_player_id, -rusher_player_id, -lateral_receiver_player_id, -lateral_receiver_player_name, -lateral_rusher_player_id, -lateral_rusher_player_name, -lateral_rushing_yards, -lateral_sack_player_id, -lateral_sack_player_name)%>%
  select(-lateral_interception_player_id, -lateral_interception_player_name, -interception_player_id, -punt_returner_player_id, -punt_returner_player_name, -lateral_punt_returner_player_id, -lateral_punt_returner_player_name, -lateral_kickoff_returner_player_id, -lateral_kickoff_returner_player_name, -kickoff_returner_player_id, -kicker_player_name, -punter_player_id, -punter_player_name, -kicker_player_id, -kicker_player_name, -blocked_player_id, -blocked_player_name, -tackle_for_loss_1_player_id, -tackle_for_loss_2_player_id, -qb_hit_1_player_id, -qb_hit_2_player_id, -forced_fumble_player_1_player_id, -forced_fumble_player_1_team, -forced_fumble_player_1_player_name, -forced_fumble_player_2_team)%>%
  select(-forced_fumble_player_2_player_id, -forced_fumble_player_2_player_name, -solo_tackle_1_team, -solo_tackle_2_team, -solo_tackle_1_player_id, -solo_tackle_2_player_id, -assist_tackle_1_team, -assist_tackle_2_team, -assist_tackle_3_team, -assist_tackle_4_team, -assist_tackle_1_player_id, -assist_tackle_2_player_id, -assist_tackle_3_player_id, -assist_tackle_4_player_id, -tackle_with_assist, -tackle_with_assist_1_player_id, -tackle_with_assist_2_player_id, -tackle_with_assist_1_team, -tackle_with_assist_2_team, -tackle_with_assist_1_player_name, -tackle_with_assist_2_player_name, -pass_defense_1_player_id, -pass_defense_2_player_id, -fumbled_1_team, -fumbled_1_player_id, -fumbled_1_player_name, -fumbled_2_team, -fumbled_2_player_id, -fumbled_2_player_name, -fumble_recovery_1_player_id)%>%
  select(-fumble_recovery_1_player_name, -fumble_recovery_1_team, -fumble_recovery_1_yards, -fumble_recovery_2_player_id, -fumble_recovery_2_team, -fumble_recovery_2_player_name, -fumble_recovery_2_yards, -sack_player_id, -half_sack_1_player_id, -half_sack_2_player_id, -return_team, -return_yards, -penalty_player_id, -penalty_player_name, -penalty_yards, -penalty_type, -replay_or_challenge, -replay_or_challenge_result, -defensive_two_point_attempt, -defensive_two_point_conv, -defensive_extra_point_attempt, -defensive_extra_point_conv, -safety_player_id, -safety_player_name, -season, -cp, -series, -series_success, -series_result, -order_sequence, -start_time, -time_of_day, -stadium, -weather, -nfl_api_id, -play_clock, -play_deleted, -special_teams_play, -st_play_type, -end_clock_time, -end_yard_line, -fixed_drive, -fixed_drive_result, -drive_real_start_time, -drive_play_count, -drive_time_of_possession, -drive_first_downs, -drive_inside20)%>%
  select(-drive_ended_with_score, -drive_quarter_start, -drive_quarter_end, -drive_yards_penalized, -drive_start_transition, -drive_end_transition, -drive_game_clock_start, -drive_game_clock_end, -drive_start_yard_line, -drive_end_yard_line, -drive_play_id_started, -drive_play_id_ended, -away_score, -home_score, -location, -result, -total, -spread_line, -div_game, -roof, -surface, -temp, -wind, -home_coach, -away_coach, -stadium_id, -game_stadium, -aborted_play, -passer, -passer_jersey_number, -rusher, -rusher_jersey_number, -receiver, -receiver_jersey_number, -special, -play, -passer_id, -rusher_id, -receiver_id, -name, -jersey_number, -id, -fantasy_player_name, -fantasy_player_id, -fantasy, -fantasy_id, -out_of_bounds, -home_opening_kickoff)
```





